// Maps irregular past-simple verb forms to their base (present) form.
// Shared by spelling (to avoid false-positive "corrections"), subject-verb
// agreement (to avoid re-conjugating already-correct past tense), and
// active-to-passive conversion (to find the base verb for participle lookup).
export const IRREGULAR_PAST_SIMPLE_TO_BASE = {
  wrote: "write",
  ate: "eat",
  saw: "see",
  went: "go",
  gave: "give",
  took: "take",
  broke: "break",
  spoke: "speak",
  drove: "drive",
  rode: "ride",
  sang: "sing",
  drank: "drink",
  swam: "swim",
  flew: "fly",
  grew: "grow",
  knew: "know",
  threw: "throw",
  wore: "wear",
  tore: "tear",
  chose: "choose",
  stole: "steal",
  fell: "fall",
  forgot: "forget",
  hid: "hide",
  bit: "bite",
  beat: "beat",
  did: "do",
  drew: "draw",
  showed: "show",
  bought: "buy",
  brought: "bring",
  caught: "catch",
  taught: "teach",
  found: "find",
  made: "make",
  sent: "send",
  spent: "spend",
  sold: "sell",
  told: "tell",
  kept: "keep",
  left: "leave",
  lost: "lose",
  met: "meet",
  paid: "pay",
};