// Maps a base verb to its past participle form, used to construct
// passive voice ("is/was + past participle"). Past participles often
// differ from simple past tense (e.g. "wrote" vs "written").
// Reference: Wren & Martin, Ch. 22 — Active and Passive Voice.
export const PAST_PARTICIPLES = {
  eat: "eaten",
  write: "written",
  read: "read",
  see: "seen",
  give: "given",
  take: "taken",
  break: "broken",
  speak: "spoken",
  drive: "driven",
  ride: "ridden",
  sing: "sung",
  drink: "drunk",
  swim: "swum",
  fly: "flown",
  grow: "grown",
  know: "known",
  throw: "thrown",
  wear: "worn",
  tear: "torn",
  choose: "chosen",
  steal: "stolen",
  fall: "fallen",
  forget: "forgotten",
  hide: "hidden",
  bite: "bitten",
  beat: "beaten",
  do: "done",
  go: "gone",
  show: "shown",
  draw: "drawn",

  // Common regular / weak verbs where past simple and participle match
  play: "played",
  watch: "watched",
  clean: "cleaned",
  cook: "cooked",
  wash: "washed",
  paint: "painted",
  build: "built",
  buy: "bought",
  bring: "brought",
  catch: "caught",
  teach: "taught",
  find: "found",
  make: "made",
  send: "sent",
  spend: "spent",
  sell: "sold",
  tell: "told",
  keep: "kept",
  leave: "left",
  lose: "lost",
  meet: "met",
  pay: "paid",
  cut: "cut",
  hit: "hit",
  hurt: "hurt",
  put: "put",
};